version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

    groups:
      maven-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

      github-actions-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action/*"
        update-types:
          - "minor"
          - "patch"
