package io.qwenbridge.threat.model;

public enum ThreatType {
  SQL_INJECTION,
  XSS,
  PROMPT_INJECTION,
  COMMAND_INJECTION,
  PATH_TRAVERSAL,
  TEMPLATE_INJECTION,
  NOSQL_INJECTION,
  LDAP_INJECTION,
  SSRF,
  SECRET_LEAKAGE,
  JAILBREAK,
  UNICODE_OBFUSCATION,
  UNKNOWN
}
