name: Feature
description: Propose a feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should this feature achieve?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is included and excluded?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
    validations:
      required: true
